openapi: 3.0.3
info:
  title: API Control Horario
  description: API REST para gestionar fichajes, usuarios, trabajos y ApiKeys.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /login:
    post:
      summary: Login de usuario
      description: Valida las credenciales y devuelve información del usuario y token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  type: string
                clave:
                  type: string
      responses:
        '200':
          description: Usuario validado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  rol:
                    type: string
                  usuarioId:
                    type: integer
        '401':
          description: Credenciales incorrectas

  /usuarios:
    get:
      summary: Lista todos los usuarios
      responses:
        '200':
          description: Listado de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      summary: Crea un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado
    put:
      summary: Actualiza un usuario existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '200':
          description: Usuario actualizado
    delete:
      summary: Borra un usuario
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Usuario eliminado

  /trabajos:
    get:
      summary: Lista todos los trabajos
      responses:
        '200':
          description: Listado de trabajos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trabajo'
    post:
      summary: Crea un nuevo trabajo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trabajo'
      responses:
        '201':
          description: Trabajo creado
    put:
      summary: Actualiza un trabajo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trabajo'
      responses:
        '200':
          description: Trabajo actualizado
    delete:
      summary: Elimina un trabajo
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Trabajo eliminado

  /fichajes:
    get:
      summary: Lista todos los fichajes o filtra por usuario/fechas
      parameters:
        - in: query
          name: idUsuario
          schema:
            type: integer
        - in: query
          name: fechaInicio
          schema:
            type: string
            format: date-time
        - in: query
          name: fechaFin
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Listado de fichajes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fichaje'
    post:
      summary: Registra un nuevo fichaje (inicio)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fichaje'
      responses:
        '201':
          description: Fichaje creado
    put:
      summary: Cierra un fichaje (añade hora de salida)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fichaje'
      responses:
        '200':
          description: Fichaje actualizado

  /apikey:
    get:
      summary: Lista todas las ApiKeys
      responses:
        '200':
          description: Listado de ApiKeys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiKey'
    post:
      summary: Crea una nueva ApiKey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiKey'
      responses:
        '201':
          description: ApiKey creada
    delete:
      summary: Elimina una ApiKey
      parameters:
        - in: query
          name: idKey
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: ApiKey eliminada

components:
  schemas:
    Usuario:
      type: object
      properties:
        IdUsuario:
          type: integer
        Nombre:
          type: string
        Usuario:
          type: string
        Clave:
          type: string
        Rol:
          type: string
          enum: [ADMIN, USER]
    Trabajo:
      type: object
      properties:
        IdTrabajo:
          type: integer
        Nombre:
          type: string
    Fichaje:
      type: object
      properties:
        IdFichaje:
          type: integer
        FechaHoraEntrada:
          type: string
          format: date-time
        FechaHoraSalida:
          type: string
          format: date-time
        HorasTrabajadas:
          type: integer
        IdTrabajo:
          type: integer
        IdUsuario:
          type: integer
        GeolocalizacionLatitud:
          type: number
          format: float
        GeolocalizacionLongitud:
          type: number
          format: float
    ApiKey:
      type: object
      properties:
        idKey:
          type: integer
        Key:
          type: string
